---
abstract: 'simple role for MIME::Types support'
author:
  - 'Fitz Elliott <felliott@fiskur.org>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebApp-Helpers-MimeTypes
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  WebApp::Helpers::MimeTypes:
    file: lib/WebApp/Helpers/MimeTypes.pm
    version: '0.01'
requires:
  MIME::Types: '0'
  Moo::Role: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/felliott/WebApp-Helpers-MimeTypes/issues
  homepage: https://github.com/felliott/WebApp-Helpers-MimeTypes
  repository: git://github.com/felliott/WebApp-Helpers-MimeTypes.git
version: '0.01'
x_authority: cpan:FELLIOTT
